### ISSUE TITLE
Excluded {} empty transcripts error

### ISSUE THREAD

**Issue by lunixbochs** [mozilla/DSAlign#20]
```
Traceback (most recent call last):
  File "align/align.py", line 673, in <module>
    main()
  File "align/align.py", line 640, in main
    logging.debug('Excluded {} empty transcripts'.format(len(transcripts) - len(fragments)))
TypeError: object of type 'IMapIterator' has no len()
```

**Comment by tilmankamp** [comment]
Fixed as part of 7fa6773bc470790def5f38ea2453ea34cb628d5a .
