### ISSUE TITLE
./bin/lm-dependencies.sh is failing because some files are missing

### ISSUE THREAD

**Issue by shivamiitgoa** [mozilla/DSAlign#34]
Error:
```
Downloading https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.deepspeech.native_client.v0.6.0.cpu/artifacts/public/native_client.tar.xz ...
Traceback (most recent call last):
  File "/home/ubuntu/DSAlign/bin/taskcluster.py", line 153, in <module>
    main()
  File "/home/ubuntu/DSAlign/bin/taskcluster.py", line 147, in main
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact, args.branch))
  File "/home/ubuntu/DSAlign/bin/taskcluster.py", line 57, in maybe_download_tc
    urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by shivam-learngram-ai** [comment]
The codes from this PR (https://github.com/mozilla/DSAlign/pull/32) fixed the issue in my case.

**Comment by tilmankamp** [comment]
This should work again.

**Comment by agnusmaximus** [comment]
Hm, seems this is not working again for 0.7.1, is there a way to work around this?

**Comment by Tortoise17** [comment]
It is working perfectly with 0.7.1. what error you are facing?

**Comment by agnusmaximus** [comment]
urllib.error.HTTPError: HTTP Error 404: Not Found for native_client v0.7.1. I believe if you already have the native_client downloaded previously, it won't download (and won't error), but if you remove the cached file, then downloading leads to the http error.

**Comment by Tortoise17** [comment]
check with 
`pip list `
inside your environment
```
deepspeech                    0.7.1
ds-ctcdecoder                 0.7.1
```

it should be available. You don't need anything else then. only requirements,.

**Comment by agnusmaximus** [comment]
Without per-document language models, it works fine, but I'm trying to get it to work with per-document language models (which I'm running into the lm-dependencies issue posted above, but for native-client v0.7.1)

**Comment by Tortoise17** [comment]
Pre-document means?

**Comment by Tortoise17** [comment]
You mean pretrained? by deepspeech?

**Comment by agnusmaximus** [comment]
I've since fixed the issue. Thanks!
