### ISSUE TITLE
Unable to generate document specific language model

### ISSUE THREAD

**Issue by bwang482** [mozilla/DSAlign#9]
I cannot seem to generate document specific language model and perform speech alignment with the command below:
`bin/align.sh --output-max-cer 15 --loglevel 10 --audio data/14001-voice.wav --script data/14001.txt --aligned data/14001.aligned.json --tlog data/14001.log.txt`

I have just installed and configured everything following the instructions. The two examples provided seem to work fine. However when I switch to my data, the error below occurs. Is this because my script file does not contain enough words?

> DEBUG:root:Start
> DEBUG:root:Looking for model files in "models/en"...
> DEBUG:root:Loading alphabet from "models/en/alphabet.txt"...
> === 1/5 Counting and sorting n-grams ===
> Reading /mnt/sdb/Tools/DSAlign/data/14001.txt.clean
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ****************************************************************************************************
> Unigram tokens 3370 types 698
> === 2/5 Calculating and sorting adjusted counts ===
> Chain sizes: 1:8376 2:31559028736 3:59173183488 4:94677090304 5:138070753280
> /mnt/sdb/Tools/DSAlign/dependencies/kenlm/lm/builder/adjust_counts.cc:52 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `s.n[j] == 0'.
> Could not calculate Kneser-Ney discounts for 5-grams with adjusted count 4 because we didn't observe any 5-grams with adjusted count 3; Is this small or artificial data?
> Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback
> 
> Traceback (most recent call last):
>   File "/mnt/sdb/Tools/DSAlign/align/align.py", line 653, in <module>
>     main()
>   File "/mnt/sdb/Tools/DSAlign/align/align.py", line 563, in main
>     '5'
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['dependencies/kenlm/build/bin/lmplz', '--text', 'data/14001.txt.clean', '--arpa', 'data/14001.txt.arpa', '--o', '5']' died with <Signals.SIGABRT: 6>.

**Comment by bwang482** [comment]
Problem solved by adding `--discount_fallback` in line 564 of `align.py`. The error described above occurs when data is small.
